---

- name: Upgrading all packages (Ubuntu/Debian)
  become: yes
  apt:
    upgrade: dist
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Upgrading all packages (Fedora)
  become: yes
  dnf:
    name: '*'
    state: latest
  when: ansible_os_family == "RedHat"

- name: "Install common packages"
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - git
    - inxi
    - python3-pip
    - python3-notebook
    - python3-seaborn
    - python3-lxml
    - python3-basemap
    - python3-scikit-image
    - python3-scikit-learn
    - python3-sympy
    - mathjax
    - tree
    - mosh
    - vim
    - keychain

- name: "Install Debian Family packages"
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - linux-tools-generic
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: "Install RedHat Family packages"
  become: yes
  package:
    name: "{{item}}"
    state: latest
  with_items:
    - perf
  when: ansible_os_family == "RedHat"


- name: "Install python modules"
  pip:
    name: ["dnspython", "requests", "SQLAlchemy", "urllib3", "xgboost"]
    extra_args: --user
    executable: pip3
    state: latest
