---

- name: Ensure SSHD boots
  become: yes
  file:
    path: /etc/ssh/sshd_not_to_be_run
    state: absent

- name: Start SSH
  become: yes
  service:
    name: ssh
    enabled: yes
    state: started
  when: ansible_os_family == "Debian" or ansible_os_family == "Ubuntu"

- name: Start SSH
  become: yes
  service:
    name: sshd
    enabled: yes
    state: started
  when: ansible_os_family == "RedHat"

- name: Load keys from keychain if present
  lineinfile:
      path: "{{ansible_env.HOME}}/.bashrc"
      line: "test -f $HOME/.keychain/$HOSTNAME-sh && . $HOME/.keychain/$HOSTNAME-sh"
